dataset:
  raw_dir: data/raw/wildtrack.v1i.yolov8
  processed_dir: data/processed
  annotation_format: yolov8
  train: data/raw/wildtrack.v1i.yolov8/train
  val: data/raw/wildtrack.v1i.yolov8/val
  test: data/raw/wildtrack.v1i.yolov8/test
  cameras:
    - cam1
    - cam2
    - cam3
    - cam4
    - cam5
    - cam6
    - cam7

calibration:
  file: configs/calibration.json
